[2024-11-08T21:42:21.866+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-08T21:42:21.903+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_postgres manual__2024-11-08T21:41:49.798723+00:00 [queued]>
[2024-11-08T21:42:21.910+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_postgres manual__2024-11-08T21:41:49.798723+00:00 [queued]>
[2024-11-08T21:42:21.911+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-08T21:42:21.924+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_data_from_postgres> on 2024-11-08 21:41:49.798723+00:00
[2024-11-08T21:42:21.929+0000] {standard_task_runner.py:64} INFO - Started process 429 to run task
[2024-11-08T21:42:21.932+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'fetch_data_from_postgres', 'manual__2024-11-08T21:41:49.798723+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/pipline.py', '--cfg-path', '/tmp/tmpnt5f3shc']
[2024-11-08T21:42:21.936+0000] {standard_task_runner.py:91} INFO - Job 65: Subtask fetch_data_from_postgres
[2024-11-08T21:42:21.989+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.fetch_data_from_postgres manual__2024-11-08T21:41:49.798723+00:00 [running]> on host ea2549ac0aa6
[2024-11-08T21:42:22.070+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_from_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-08T21:41:49.798723+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-08T21:41:49.798723+00:00'
[2024-11-08T21:42:22.072+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-08T21:42:22.081+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-11-08T21:42:22.144+0000] {logging_mixin.py:188} INFO - Error connecting to PostgreSQL: could not translate host name "host.docker.local" to address: Name or service not known
[2024-11-08T21:42:22.144+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-08T21:42:22.146+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-08T21:42:22.154+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=fetch_data_from_postgres, run_id=manual__2024-11-08T21:41:49.798723+00:00, execution_date=20241108T214149, start_date=20241108T214221, end_date=20241108T214222
[2024-11-08T21:42:22.185+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-08T21:42:22.205+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-08T21:42:22.208+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
