[2024-11-08T21:28:39.873+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-08T21:28:39.906+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_json scheduled__2024-11-07T00:00:00+00:00 [queued]>
[2024-11-08T21:28:39.918+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_json scheduled__2024-11-07T00:00:00+00:00 [queued]>
[2024-11-08T21:28:39.920+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-08T21:28:39.936+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_data_from_json> on 2024-11-07 00:00:00+00:00
[2024-11-08T21:28:39.941+0000] {standard_task_runner.py:64} INFO - Started process 233 to run task
[2024-11-08T21:28:39.945+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'fetch_data_from_json', 'scheduled__2024-11-07T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/pipline.py', '--cfg-path', '/tmp/tmp1vb3guq8']
[2024-11-08T21:28:39.947+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask fetch_data_from_json
[2024-11-08T21:28:39.993+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.fetch_data_from_json scheduled__2024-11-07T00:00:00+00:00 [running]> on host 8ed9e842b073
[2024-11-08T21:28:40.075+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_from_json' AIRFLOW_CTX_EXECUTION_DATE='2024-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-07T00:00:00+00:00'
[2024-11-08T21:28:40.077+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-08T21:28:40.078+0000] {logging_mixin.py:188} INFO - Error reading JSON file: [Errno 2] No such file or directory: '../data_set/journals.json'
[2024-11-08T21:28:40.078+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-08T21:28:40.079+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-08T21:28:40.086+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=fetch_data_from_json, run_id=scheduled__2024-11-07T00:00:00+00:00, execution_date=20241107T000000, start_date=20241108T212839, end_date=20241108T212840
[2024-11-08T21:28:40.117+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-08T21:28:40.136+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-08T21:28:40.139+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
