[2024-11-09T17:49:01.790+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-09T17:49:01.902+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_mongo manual__2024-11-09T17:49:00.703350+00:00 [queued]>
[2024-11-09T17:49:01.936+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_mongo manual__2024-11-09T17:49:00.703350+00:00 [queued]>
[2024-11-09T17:49:01.949+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-09T17:49:02.032+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_data_from_mongo> on 2024-11-09 17:49:00.703350+00:00
[2024-11-09T17:49:02.047+0000] {standard_task_runner.py:64} INFO - Started process 403 to run task
[2024-11-09T17:49:02.063+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'fetch_data_from_mongo', 'manual__2024-11-09T17:49:00.703350+00:00', '--job-id', '346', '--raw', '--subdir', 'DAGS_FOLDER/pipline.py', '--cfg-path', '/tmp/tmp2un6xdmj']
[2024-11-09T17:49:02.075+0000] {standard_task_runner.py:91} INFO - Job 346: Subtask fetch_data_from_mongo
[2024-11-09T17:49:02.275+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.fetch_data_from_mongo manual__2024-11-09T17:49:00.703350+00:00 [running]> on host 35b8b9bdba09
[2024-11-09T17:49:02.588+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_from_mongo' AIRFLOW_CTX_EXECUTION_DATE='2024-11-09T17:49:00.703350+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-09T17:49:00.703350+00:00'
[2024-11-09T17:49:02.593+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-09T17:49:02.632+0000] {base.py:84} INFO - Using connection ID 'mongo_default' for task execution.
[2024-11-09T17:49:33.358+0000] {logging_mixin.py:188} INFO - Error connecting to MongoDB: SSL handshake failed: journals-shard-00-02.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: journals-shard-00-00.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: journals-shard-00-01.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 672fa08fbcce0459d4bfc869, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('journals-shard-00-00.yg9j2.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: journals-shard-00-00.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('journals-shard-00-01.yg9j2.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: journals-shard-00-01.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('journals-shard-00-02.yg9j2.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: journals-shard-00-02.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2024-11-09T17:49:33.363+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-09T17:49:33.366+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-09T17:49:33.400+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=fetch_data_from_mongo, run_id=manual__2024-11-09T17:49:00.703350+00:00, execution_date=20241109T174900, start_date=20241109T174901, end_date=20241109T174933
[2024-11-09T17:49:33.436+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-09T17:49:33.473+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-09T17:49:33.476+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
