[2024-12-22T16:27:15.251+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-22T16:27:15.289+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_mongo manual__2024-12-22T16:27:13.470561+00:00 [queued]>
[2024-12-22T16:27:15.304+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_mongo manual__2024-12-22T16:27:13.470561+00:00 [queued]>
[2024-12-22T16:27:15.310+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-22T16:27:15.332+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_data_from_mongo> on 2024-12-22 16:27:13.470561+00:00
[2024-12-22T16:27:15.337+0000] {standard_task_runner.py:64} INFO - Started process 209 to run task
[2024-12-22T16:27:15.343+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'fetch_data_from_mongo', 'manual__2024-12-22T16:27:13.470561+00:00', '--job-id', '736', '--raw', '--subdir', 'DAGS_FOLDER/pipline.py', '--cfg-path', '/tmp/tmp4qs3kuhk']
[2024-12-22T16:27:15.347+0000] {standard_task_runner.py:91} INFO - Job 736: Subtask fetch_data_from_mongo
[2024-12-22T16:27:15.409+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.fetch_data_from_mongo manual__2024-12-22T16:27:13.470561+00:00 [running]> on host 2ac427f360a6
[2024-12-22T16:27:15.540+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_from_mongo' AIRFLOW_CTX_EXECUTION_DATE='2024-12-22T16:27:13.470561+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-22T16:27:13.470561+00:00'
[2024-12-22T16:27:15.542+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-22T16:27:15.555+0000] {base.py:84} INFO - Using connection ID 'mongo_default' for task execution.
[2024-12-22T16:27:46.558+0000] {logging_mixin.py:188} INFO - Error connecting to MongoDB: SSL handshake failed: journals-shard-00-02.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: journals-shard-00-01.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: journals-shard-00-00.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 67683de4cc030ed69cf889d9, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('journals-shard-00-00.yg9j2.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: journals-shard-00-00.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('journals-shard-00-01.yg9j2.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: journals-shard-00-01.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('journals-shard-00-02.yg9j2.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: journals-shard-00-02.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2024-12-22T16:27:46.560+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-22T16:27:46.562+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-22T16:27:46.619+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=fetch_data_from_mongo, run_id=manual__2024-12-22T16:27:13.470561+00:00, execution_date=20241222T162713, start_date=20241222T162715, end_date=20241222T162746
[2024-12-22T16:27:46.666+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-12-22T16:27:46.697+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-22T16:27:46.700+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
