[2024-12-24T17:50:49.995+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-24T17:50:50.022+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_mongo manual__2024-12-24T17:50:49.335943+00:00 [queued]>
[2024-12-24T17:50:50.030+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_mongo manual__2024-12-24T17:50:49.335943+00:00 [queued]>
[2024-12-24T17:50:50.031+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-24T17:50:50.043+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_data_from_mongo> on 2024-12-24 17:50:49.335943+00:00
[2024-12-24T17:50:50.048+0000] {standard_task_runner.py:64} INFO - Started process 220 to run task
[2024-12-24T17:50:50.051+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'fetch_data_from_mongo', 'manual__2024-12-24T17:50:49.335943+00:00', '--job-id', '872', '--raw', '--subdir', 'DAGS_FOLDER/pipline.py', '--cfg-path', '/tmp/tmp6ue7ask0']
[2024-12-24T17:50:50.054+0000] {standard_task_runner.py:91} INFO - Job 872: Subtask fetch_data_from_mongo
[2024-12-24T17:50:50.113+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.fetch_data_from_mongo manual__2024-12-24T17:50:49.335943+00:00 [running]> on host cd39b53ebd5d
[2024-12-24T17:50:50.213+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_from_mongo' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T17:50:49.335943+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-24T17:50:49.335943+00:00'
[2024-12-24T17:50:50.214+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-24T17:50:50.225+0000] {base.py:84} INFO - Using connection ID 'mongo_default' for task execution.
[2024-12-24T17:51:20.881+0000] {logging_mixin.py:188} INFO - Error connecting to MongoDB: SSL handshake failed: journals-shard-00-00.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: journals-shard-00-01.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: journals-shard-00-02.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 676af47a38b9e9968937f391, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('journals-shard-00-00.yg9j2.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: journals-shard-00-00.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('journals-shard-00-01.yg9j2.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: journals-shard-00-01.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('journals-shard-00-02.yg9j2.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: journals-shard-00-02.yg9j2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2024-12-24T17:51:20.882+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-24T17:51:20.884+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-24T17:51:20.896+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=fetch_data_from_mongo, run_id=manual__2024-12-24T17:50:49.335943+00:00, execution_date=20241224T175049, start_date=20241224T175050, end_date=20241224T175120
[2024-12-24T17:51:20.937+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-12-24T17:51:20.959+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-24T17:51:20.962+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
