[2024-11-10T02:26:21.315+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-10T02:26:21.346+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.insert_data_into_data_warehouse manual__2024-11-10T02:26:17.562895+00:00 [queued]>
[2024-11-10T02:26:21.358+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.insert_data_into_data_warehouse manual__2024-11-10T02:26:17.562895+00:00 [queued]>
[2024-11-10T02:26:21.359+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-10T02:26:21.375+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): insert_data_into_data_warehouse> on 2024-11-10 02:26:17.562895+00:00
[2024-11-10T02:26:21.379+0000] {standard_task_runner.py:64} INFO - Started process 196 to run task
[2024-11-10T02:26:21.383+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'insert_data_into_data_warehouse', 'manual__2024-11-10T02:26:17.562895+00:00', '--job-id', '486', '--raw', '--subdir', 'DAGS_FOLDER/pipline.py', '--cfg-path', '/tmp/tmpot9g7s8m']
[2024-11-10T02:26:21.386+0000] {standard_task_runner.py:91} INFO - Job 486: Subtask insert_data_into_data_warehouse
[2024-11-10T02:26:21.442+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.insert_data_into_data_warehouse manual__2024-11-10T02:26:17.562895+00:00 [running]> on host 5a1264ed2193
[2024-11-10T02:26:21.825+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='insert_data_into_data_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T02:26:17.562895+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T02:26:17.562895+00:00'
[2024-11-10T02:26:21.828+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-10T02:26:21.849+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:21.888+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:21.903+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:21.919+0000] {pipline.py:266} ERROR - Error processing publication 'Assessing Trustworthy AI in Times of COVID-19: Deep Learning for Predicting a Multiregional Score Conveying the Degree of Lung Compromise in COVID-19 Patients': 'str' object has no attribute 'get'
[2024-11-10T02:26:21.925+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:21.943+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:21.950+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:21.967+0000] {pipline.py:266} ERROR - Error processing publication 'It is Not “Accuracy vs. Explainability”—We Need Both for Trustworthy AI Systems': 'str' object has no attribute 'get'
[2024-11-10T02:26:21.979+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:21.997+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:22.007+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.033+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.073+0000] {pipline.py:235} INFO - Publication 'The Generative AI Landscape in Education: Mapping the Terrain of Opportunities, Challenges, and Student Perception' inserted successfully.
[2024-11-10T02:26:22.080+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.093+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:22.100+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.113+0000] {pipline.py:266} ERROR - Error processing publication 'SmartQuant: CXL-Based AI Model Store in Support of Runtime Configurable Weight Quantization': 'str' object has no attribute 'get'
[2024-11-10T02:26:22.124+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.145+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:22.151+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.162+0000] {pipline.py:266} ERROR - Error processing publication 'mTREE: A Customized Multicast-Enabled Tree-Based Network on Chip for AI Chips': 'str' object has no attribute 'get'
[2024-11-10T02:26:22.168+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.179+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:22.185+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.203+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.224+0000] {pipline.py:235} INFO - Publication 'A Survey of Real-Time Strategy Game AI Research and Competition in StarCraft' inserted successfully.
[2024-11-10T02:26:22.231+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.241+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:22.247+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.265+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.288+0000] {pipline.py:235} INFO - Publication 'Unraveling ML Models of Emotion With NOVA: Multi-Level Explainable AI for Non-Experts' inserted successfully.
[2024-11-10T02:26:22.295+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.305+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:22.311+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.327+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.348+0000] {pipline.py:235} INFO - Publication 'AIS-PVT: Long-Time AIS Data Assisted Pyramid Vision Transformer for Sea-Land Segmentation in Dual-Polarization SAR Imagery' inserted successfully.
[2024-11-10T02:26:22.355+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.366+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:22.372+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.391+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.414+0000] {pipline.py:235} INFO - Publication 'Explainable AI for Cheating Detection and Churn Prediction in Online Games' inserted successfully.
[2024-11-10T02:26:22.420+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.430+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:22.436+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.453+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.476+0000] {pipline.py:235} INFO - Publication 'Towards Measuring Fairness in AI: The Casual Conversations Dataset' inserted successfully.
[2024-11-10T02:26:22.481+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.492+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:22.498+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.517+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.538+0000] {pipline.py:235} INFO - Publication 'Personas for Artificial Intelligence (AI) an Open Source Toolbox' inserted successfully.
[2024-11-10T02:26:22.544+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.555+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:22.561+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.579+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.602+0000] {pipline.py:235} INFO - Publication 'A Game AI Competition to Foster Collaborative AI Research and Development' inserted successfully.
[2024-11-10T02:26:22.609+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.619+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:22.625+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.637+0000] {pipline.py:266} ERROR - Error processing publication 'Toward a Policy Approach to Normative Artificial Intelligence Governance: Implications for AI Ethics Education': 'str' object has no attribute 'get'
[2024-11-10T02:26:22.644+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.654+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:22.661+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.678+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.699+0000] {pipline.py:235} INFO - Publication 'XAI-IoT: An Explainable AI Framework for Enhancing Anomaly Detection in IoT Systems' inserted successfully.
[2024-11-10T02:26:22.705+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.716+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:22.722+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.739+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.765+0000] {pipline.py:235} INFO - Publication 'Human-Centered AI in Smart Farming: Toward Agriculture 5.0' inserted successfully.
[2024-11-10T02:26:22.771+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.780+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:22.787+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.804+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.824+0000] {pipline.py:235} INFO - Publication 'An Area-Efficient Systolic Array Redundancy Architecture for Reliable AI Accelerator' inserted successfully.
[2024-11-10T02:26:22.830+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.840+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:22.845+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.862+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.886+0000] {pipline.py:235} INFO - Publication 'Unleashing the Power of Edge-Cloud Generative AI in Mobile Networks: A Survey of AIGC Services' inserted successfully.
[2024-11-10T02:26:22.893+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.902+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:22.908+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.925+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.947+0000] {pipline.py:235} INFO - Publication 'Exploring the Effect of Generative AI on Social Sustainability Through Integrating AI Attributes, TPB, and T-EESST: A Deep Learning-Based Hybrid SEM-ANN Approach' inserted successfully.
[2024-11-10T02:26:22.954+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.963+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:22.971+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:22.995+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.022+0000] {pipline.py:235} INFO - Publication 'The Ethics of AI in Games' inserted successfully.
[2024-11-10T02:26:23.029+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.039+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:23.046+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.070+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.098+0000] {pipline.py:235} INFO - Publication 'E-XAI: Evaluating Black-Box Explainable AI Frameworks for Network Intrusion Detection' inserted successfully.
[2024-11-10T02:26:23.107+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.121+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:23.129+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.152+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.179+0000] {pipline.py:235} INFO - Publication 'Demystifying Defects: Federated Learning and Explainable AI for Semiconductor Fault Detection' inserted successfully.
[2024-11-10T02:26:23.186+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.200+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:23.207+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.230+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.257+0000] {pipline.py:235} INFO - Publication 'Developing a Transparent Diagnosis Model for Diabetic Retinopathy Using Explainable AI' inserted successfully.
[2024-11-10T02:26:23.264+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.277+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:23.284+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.306+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.335+0000] {pipline.py:235} INFO - Publication 'AI and Security, From an Information Security and Risk Manager Standpoint' inserted successfully.
[2024-11-10T02:26:23.343+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.356+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:23.364+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.387+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.420+0000] {pipline.py:235} INFO - Publication 'Empirical Evaluations of Framework for Adaptive Trust Calibration in Human-AI Cooperation' inserted successfully.
[2024-11-10T02:26:23.428+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.441+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:23.449+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.465+0000] {pipline.py:266} ERROR - Error processing publication 'Assessing Trustworthy AI in Times of COVID-19: Deep Learning for Predicting a Multiregional Score Conveying the Degree of Lung Compromise in COVID-19 Patients': 'str' object has no attribute 'get'
[2024-11-10T02:26:23.471+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.488+0000] {pipline.py:168} ERROR - Error adding authors: 'str' object has no attribute 'get'
[2024-11-10T02:26:23.495+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2024-11-10T02:26:23.511+0000] {pipline.py:266} ERROR - Error processing publication 'It is Not “Accuracy vs. Explainability”—We Need Both for Trustworthy AI Systems': 'str' object has no attribute 'get'
[2024-11-10T02:26:23.512+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-10T02:26:23.513+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-10T02:26:23.522+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=insert_data_into_data_warehouse, run_id=manual__2024-11-10T02:26:17.562895+00:00, execution_date=20241110T022617, start_date=20241110T022621, end_date=20241110T022623
[2024-11-10T02:26:23.564+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-10T02:26:23.592+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-10T02:26:23.594+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
