[2024-11-08T13:31:23.258+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:31:23.259+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:31:23.261+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:31:23.261+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:31:23.287+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:31:23.283+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:31:23.290+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:31:23.310+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.060 seconds
[2024-11-08T13:31:53.543+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:31:53.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:31:53.546+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:31:53.545+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:31:53.560+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:31:53.556+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:31:53.561+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:31:53.576+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.038 seconds
[2024-11-08T13:32:24.077+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:32:24.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:32:24.079+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:32:24.079+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:32:24.095+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:32:24.091+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:32:24.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:32:24.117+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.045 seconds
[2024-11-08T13:32:54.591+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:32:54.591+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:32:54.593+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:32:54.592+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:32:54.607+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:32:54.604+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:32:54.608+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:32:54.627+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.041 seconds
[2024-11-08T13:33:25.093+0000] {processor.py:161} INFO - Started process (PID=250) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:33:25.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:33:25.095+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:33:25.095+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:33:25.116+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:33:25.110+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:33:25.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:33:25.146+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.058 seconds
[2024-11-08T13:33:55.585+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:33:55.586+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:33:55.587+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:33:55.587+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:33:55.602+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:33:55.598+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:33:55.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:33:55.680+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.101 seconds
[2024-11-08T13:34:26.120+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:34:26.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:34:26.122+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:34:26.122+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:34:26.140+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:34:26.136+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:34:26.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:34:26.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.044 seconds
[2024-11-08T13:34:56.651+0000] {processor.py:161} INFO - Started process (PID=313) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:34:56.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:34:56.653+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:34:56.653+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:34:56.668+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:34:56.665+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:34:56.670+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:34:56.688+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.044 seconds
[2024-11-08T13:35:27.176+0000] {processor.py:161} INFO - Started process (PID=334) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:35:27.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:35:27.179+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:35:27.178+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:35:27.195+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:35:27.192+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:35:27.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:35:27.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.151 seconds
[2024-11-08T13:35:57.810+0000] {processor.py:161} INFO - Started process (PID=355) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:35:57.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:35:57.813+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:35:57.813+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:35:57.827+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:35:57.823+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:35:57.828+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:35:57.845+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.041 seconds
[2024-11-08T13:36:28.394+0000] {processor.py:161} INFO - Started process (PID=376) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:36:28.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:36:28.398+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:36:28.397+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:36:28.414+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:36:28.410+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:36:28.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:36:28.436+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.047 seconds
[2024-11-08T13:36:58.769+0000] {processor.py:161} INFO - Started process (PID=397) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:36:58.769+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:36:58.771+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:36:58.771+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:36:58.788+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:36:58.785+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:36:58.789+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:36:58.808+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.046 seconds
[2024-11-08T13:37:29.114+0000] {processor.py:161} INFO - Started process (PID=418) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:37:29.114+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:37:29.116+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:37:29.116+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:37:29.132+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:37:29.128+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:37:29.134+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:37:29.154+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.046 seconds
[2024-11-08T13:37:59.476+0000] {processor.py:161} INFO - Started process (PID=439) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:37:59.479+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:37:59.482+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:37:59.481+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:37:59.505+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:37:59.501+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:37:59.507+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:37:59.541+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.076 seconds
[2024-11-08T13:38:29.818+0000] {processor.py:161} INFO - Started process (PID=460) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:38:29.819+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:38:29.821+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:38:29.821+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:38:29.835+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:38:29.831+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:38:29.836+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:38:29.853+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.040 seconds
[2024-11-08T13:39:00.192+0000] {processor.py:161} INFO - Started process (PID=481) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:39:00.193+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:39:00.196+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:39:00.195+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:39:00.211+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:39:00.208+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:39:00.212+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:39:00.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.046 seconds
[2024-11-08T13:39:30.703+0000] {processor.py:161} INFO - Started process (PID=502) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:39:30.704+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:39:30.705+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:39:30.705+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:39:30.719+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:39:30.716+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:39:30.720+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:39:30.736+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.039 seconds
[2024-11-08T13:40:01.053+0000] {processor.py:161} INFO - Started process (PID=523) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:40:01.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:40:01.056+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:40:01.056+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:40:01.072+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:40:01.069+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:40:01.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:40:01.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.045 seconds
[2024-11-08T13:40:31.392+0000] {processor.py:161} INFO - Started process (PID=544) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:40:31.393+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:40:31.395+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:40:31.395+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:40:31.409+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:40:31.406+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:40:31.410+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:40:31.428+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.041 seconds
[2024-11-08T13:41:01.748+0000] {processor.py:161} INFO - Started process (PID=565) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:41:01.749+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:41:01.751+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:41:01.751+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:41:01.766+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:41:01.763+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:41:01.767+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:41:01.786+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.045 seconds
[2024-11-08T13:41:32.084+0000] {processor.py:161} INFO - Started process (PID=586) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:41:32.085+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:41:32.086+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:41:32.086+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:41:32.099+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:41:32.096+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:41:32.101+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:41:32.118+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.040 seconds
[2024-11-08T13:42:02.427+0000] {processor.py:161} INFO - Started process (PID=607) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:42:02.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:42:02.430+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:42:02.429+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:42:02.445+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:42:02.442+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:42:02.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:42:02.463+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.041 seconds
[2024-11-08T13:42:32.778+0000] {processor.py:161} INFO - Started process (PID=628) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:42:32.779+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:42:32.781+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:42:32.781+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:42:32.798+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:42:32.794+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:42:32.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:42:32.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.055 seconds
[2024-11-08T13:43:03.134+0000] {processor.py:161} INFO - Started process (PID=650) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:43:03.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:43:03.137+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:43:03.136+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:43:03.156+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:43:03.153+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:43:03.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:43:03.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.048 seconds
[2024-11-08T13:43:33.427+0000] {processor.py:161} INFO - Started process (PID=671) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:43:33.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:43:33.430+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:43:33.429+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:43:33.445+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:43:33.441+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:43:33.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:43:33.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.057 seconds
[2024-11-08T13:44:03.912+0000] {processor.py:161} INFO - Started process (PID=692) to work on /opt/airflow/dags/mongo_db.py
[2024-11-08T13:44:03.913+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mongo_db.py for tasks to queue
[2024-11-08T13:44:03.915+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:44:03.915+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:44:03.933+0000] {logging_mixin.py:188} INFO - [2024-11-08T13:44:03.929+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/mongo_db.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_db.py", line 4, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2024-11-08T13:44:03.934+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_db.py
[2024-11-08T13:44:03.955+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mongo_db.py took 0.049 seconds
