[2024-11-08T22:13:27.865+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-08T22:13:27.892+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_postgres manual__2024-11-08T22:13:24.170461+00:00 [queued]>
[2024-11-08T22:13:27.899+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_postgres manual__2024-11-08T22:13:24.170461+00:00 [queued]>
[2024-11-08T22:13:27.901+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-08T22:13:27.911+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_data_from_postgres> on 2024-11-08 22:13:24.170461+00:00
[2024-11-08T22:13:27.915+0000] {standard_task_runner.py:64} INFO - Started process 1788 to run task
[2024-11-08T22:13:27.920+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'fetch_data_from_postgres', 'manual__2024-11-08T22:13:24.170461+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/pipline.py', '--cfg-path', '/tmp/tmpbi6f7ol_']
[2024-11-08T22:13:27.922+0000] {standard_task_runner.py:91} INFO - Job 92: Subtask fetch_data_from_postgres
[2024-11-08T22:13:27.963+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.fetch_data_from_postgres manual__2024-11-08T22:13:24.170461+00:00 [running]> on host ea2549ac0aa6
[2024-11-08T22:13:28.043+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_from_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-08T22:13:24.170461+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-08T22:13:24.170461+00:00'
[2024-11-08T22:13:28.044+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-08T22:13:28.051+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-11-08T22:13:28.113+0000] {logging_mixin.py:188} INFO - Error connecting to PostgreSQL: could not translate host name "host.docker.local" to address: Name or service not known
[2024-11-08T22:13:28.113+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-08T22:13:28.114+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-08T22:13:28.121+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=fetch_data_from_postgres, run_id=manual__2024-11-08T22:13:24.170461+00:00, execution_date=20241108T221324, start_date=20241108T221327, end_date=20241108T221328
[2024-11-08T22:13:28.173+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-08T22:13:28.193+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-08T22:13:28.196+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
