[2024-11-08T22:01:21.712+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-08T22:01:21.739+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_mongo manual__2024-11-08T22:01:21.162877+00:00 [queued]>
[2024-11-08T22:01:21.747+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_mongo manual__2024-11-08T22:01:21.162877+00:00 [queued]>
[2024-11-08T22:01:21.748+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-08T22:01:21.760+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_data_from_mongo> on 2024-11-08 22:01:21.162877+00:00
[2024-11-08T22:01:21.764+0000] {standard_task_runner.py:64} INFO - Started process 1242 to run task
[2024-11-08T22:01:21.768+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'fetch_data_from_mongo', 'manual__2024-11-08T22:01:21.162877+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/pipline.py', '--cfg-path', '/tmp/tmppf7z1bwg']
[2024-11-08T22:01:21.770+0000] {standard_task_runner.py:91} INFO - Job 75: Subtask fetch_data_from_mongo
[2024-11-08T22:01:21.812+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.fetch_data_from_mongo manual__2024-11-08T22:01:21.162877+00:00 [running]> on host ea2549ac0aa6
[2024-11-08T22:01:21.892+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_from_mongo' AIRFLOW_CTX_EXECUTION_DATE='2024-11-08T22:01:21.162877+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-08T22:01:21.162877+00:00'
[2024-11-08T22:01:21.894+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-08T22:01:21.902+0000] {base.py:84} INFO - Using connection ID 'mongo_default' for task execution.
[2024-11-08T22:01:21.904+0000] {logging_mixin.py:188} INFO - Error connecting to MongoDB: Bad database name "/***:***@journals"
[2024-11-08T22:01:21.904+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-08T22:01:21.905+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-08T22:01:21.912+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=fetch_data_from_mongo, run_id=manual__2024-11-08T22:01:21.162877+00:00, execution_date=20241108T220121, start_date=20241108T220121, end_date=20241108T220121
[2024-11-08T22:01:21.940+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-08T22:01:21.962+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-08T22:01:21.965+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
